In [4]:
import numpy as np
import time

In [2]:
x = np.random.random(100000000)

In [5]:
start = time.time()
sum(x) / len(x)

print(time.time() - start)

3.5525267124176025


In [6]:
start = time.time()
np.mean(x)

print(time.time() - start)

0.02595686912536621


In [7]:
x = np.array([1, 2, 3, 4, 5])

In [8]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
x.dtype

dtype('int64')

In [10]:
x.shape

(5,)

In [11]:
Y = np.array(
    [
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
    ]
)

Y.shape

(4, 3)

In [12]:
Y.size

12

In [15]:
x = np.array(['hello', 'world'])

type(x)

numpy.ndarray

In [16]:
x.dtype

dtype('<U5')

In [17]:
x= np.array([1, 2.5, 4.3])
print(x, x.dtype, type(x))

[1.  2.5 4.3] float64 <class 'numpy.ndarray'>


In [18]:
x= np.array([1, 2.5, 4.3], dtype=np.int64)
print(x, x.dtype, type(x))

[1 2 4] int64 <class 'numpy.ndarray'>


In [19]:
lst = [1, 2, 3, 4]

np.array(lst)

array([1, 2, 3, 4])

In [21]:
X = np.zeros((3,4), dtype=int)

print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((4, 3), -1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [24]:
np.full((4, 3), 'hello')

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [112]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 20, 4)

array([ 1,  5,  9, 13, 17])

In [34]:
np.linspace(0, 100, 10, endpoint=False, dtype=int)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
np.arange(20).reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [44]:
np.linspace(0, 50, 5, endpoint=False).reshape(5)

array([ 0., 10., 20., 30., 40.])

In [45]:
X = np.random.random((3, 3))

In [46]:
X

array([[0.68379539, 0.90154138, 0.94190181],
       [0.82028557, 0.42486946, 0.69743484],
       [0.33630263, 0.27033959, 0.11286231]])

In [47]:
np.random.randint(4, 15, (3, 2))

array([[ 4,  8],
       [13,  4],
       [ 6, 12]])

In [50]:
np.linspace(2, 32, 16, dtype=int).reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [51]:
x = np.array([1,2,3,4,5])

In [52]:
x[0]

np.int64(1)

In [54]:
print(x[0])
print(x[-2])

1
4


In [55]:
x[3] = 10

In [56]:
print(x)

[ 1  2  3 10  5]


In [57]:
X = np.arange(1, 10).reshape(3, 3)

In [58]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
print(X[0, 0])
X[0, 0] = 100
print(X[0, 0])

1
100


In [79]:
X = np.arange(0, 9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
X = np.delete(X, [0,1], axis=0)
X

array([[6, 7, 8]])

In [81]:
X = np.append(X, [[9, 10, 11]], axis=0)
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
Y = np.append(X, [[12], [13], [14], [15]], axis=1)
Y

array([[ 0,  1,  2, 12],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14],
       [ 9, 10, 11, 15]])

In [84]:
x = np.insert(x, 2, [3,4])
x

array([ 1,  2,  3,  4,  3, 10,  5])

In [86]:
W = np.insert(Y, 1, [5, 6, 7, 8], axis=0)
W

array([[ 0,  1,  2, 12],
       [ 5,  6,  7,  8],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14],
       [ 9, 10, 11, 15]])

In [88]:
x = np.array([1, 2])

X = np.array([[3, 4], [5,6]])
print(x)
print(X)

[1 2]
[[3 4]
 [5 6]]


In [89]:
z = np.vstack((x, X))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
z = np.hstack((X, x.reshape(2, 1)))
z

array([[3, 4, 1],
       [5, 6, 2]])

In [91]:
X = np.arange(1, 21).reshape(4, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [92]:
z = X[1:4, 2:5]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [93]:
z = X[1:, 2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [94]:
X[:3, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [95]:
X[:, 2]

array([ 3,  8, 13, 18])

In [96]:
X[:, 2:3]

array([[ 3],
       [ 8],
       [13],
       [18]])

In [97]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [99]:
z = X[1:, 2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [100]:
z[2, 2] = 555
X

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19, 555]])

In [103]:
z = X[1:, 2:].copy()
z[2,2] = 511
X

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19, 555]])

In [104]:
z

array([[  8,   9,  10],
       [ 13,  14,  15],
       [ 18,  19, 511]])

In [107]:
np.diag(X)

array([ 1,  7, 13, 19])

In [108]:
np.diag(X, k=2)

array([ 3,  9, 15])

In [109]:
np.diag(X, k = -1)

array([ 6, 12, 18])

In [110]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
X

array([[1, 2, 3],
       [5, 2, 8],
       [1, 2, 3]])

In [111]:
np.unique(X)

array([1, 2, 3, 5, 8])

In [2]:
import numpy as np
X = np.arange(25).reshape(5,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
X[X > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
X[(X > 10) & (X < 17)]

array([11, 12, 13, 14, 15, 16])

In [14]:
X[(X > 10) & (X < 17)] = -1

X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 2, 4])

In [10]:
np.intersect1d(x, y)

array([2, 4])

In [11]:
np.setdiff1d(x, y)

array([1, 3, 5])

In [12]:
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.random.randint(1, 11, size=(10,))

In [16]:
x

array([ 8,  7,  2,  4, 10,  4,  3,  9,  7,  9])

In [17]:
np.sort(x)

array([ 2,  3,  4,  4,  7,  7,  8,  9,  9, 10])

In [18]:
np.sort(np.unique(x))

array([ 2,  3,  4,  7,  8,  9, 10])

In [19]:
x.sort()

In [20]:
x

array([ 2,  3,  4,  4,  7,  7,  8,  9,  9, 10])

In [21]:
X = np.random.randint(1, 11, size=(5, 5))
X

array([[ 6, 10,  1,  5, 10],
       [ 6,  7,  6,  8,  7],
       [ 1,  2,  2,  3, 10],
       [ 9,  2,  3,  5,  4],
       [ 5,  8,  6,  4,  8]])

In [22]:
np.sort(X, axis=0)

array([[ 1,  2,  1,  3,  4],
       [ 5,  2,  2,  4,  7],
       [ 6,  7,  3,  5,  8],
       [ 6,  8,  6,  5, 10],
       [ 9, 10,  6,  8, 10]])

In [23]:
np.sort(X, axis=1)

array([[ 1,  5,  6, 10, 10],
       [ 6,  6,  7,  7,  8],
       [ 1,  2,  2,  3, 10],
       [ 2,  3,  4,  5,  9],
       [ 4,  5,  6,  8,  8]])